apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
  {{- if .Values.installOrder.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.installOrder.providerConfigWave | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  {{- end }}
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Values.credentials.secretNamespace | quote }}
      name: {{ .Values.credentials.secretName | quote }}
      key: {{ .Values.credentials.secretKey | quote }}
